version: "3.9"
services:
  web:
    build: .
    ports:
      - "8001:8001"
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    networks:
      - myNetwork
networks:
  myNetwork:
    name: myNetwork
    driver: bridge